app:
  debug: true
  loglevel: i

display:
  imshow_source_frames: false
  imshow_motion_threshold: false
  imshow_motion_results: false
  imshow_tracker_results: false
  imshow_detection_results: true

event:
  dump_path: dumps

model:
  name: yolov8n.pt
  threshold: 0.3

source:
  url: "C:/Users/soura/Downloads/surveillance_videos/sb/Channel ID_18_3.mp4"
  reconnect_on_failure: false
  roi:
    enabled: false
    x1: null
    y1: null
    x2: null
    y2: null

motion:
  percent: 0.02

tracker:
  enabled: true
  name: cv2_TrackerCSRT